/* 
 * on-network api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type SwitchEndpoint struct {

	Ip string `json:"ip"`

	Username string `json:"username"`

	Password string `json:"password"`

	SwitchType string `json:"switchType"`
}
