// Copyright 2017, Dell EMC, Inc.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/on-network/models"
)

// AboutGetOKCode is the HTTP code returned for type AboutGetOK
const AboutGetOKCode int = 200

/*AboutGetOK Successfully retrieved about

swagger:response aboutGetOK
*/
type AboutGetOK struct {

	/*
	  In: Body
	*/
	Payload *models.About `json:"body,omitempty"`
}

// NewAboutGetOK creates AboutGetOK with default headers values
func NewAboutGetOK() *AboutGetOK {
	return &AboutGetOK{}
}

// WithPayload adds the payload to the about get o k response
func (o *AboutGetOK) WithPayload(payload *models.About) *AboutGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the about get o k response
func (o *AboutGetOK) SetPayload(payload *models.About) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AboutGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AboutGetDefault Error

swagger:response aboutGetDefault
*/
type AboutGetDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewAboutGetDefault creates AboutGetDefault with default headers values
func NewAboutGetDefault(code int) *AboutGetDefault {
	if code <= 0 {
		code = 500
	}

	return &AboutGetDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the about get default response
func (o *AboutGetDefault) WithStatusCode(code int) *AboutGetDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the about get default response
func (o *AboutGetDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the about get default response
func (o *AboutGetDefault) WithPayload(payload *models.ErrorResponse) *AboutGetDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the about get default response
func (o *AboutGetDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AboutGetDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
