// Code generated by go-swagger; DO NOT EDIT.

package switch_version

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// SwitchVersionHandlerFunc turns a function with the right signature into a switch version handler
type SwitchVersionHandlerFunc func(SwitchVersionParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SwitchVersionHandlerFunc) Handle(params SwitchVersionParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SwitchVersionHandler interface for that can handle valid switch version params
type SwitchVersionHandler interface {
	Handle(SwitchVersionParams, interface{}) middleware.Responder
}

// NewSwitchVersion creates a new http.Handler for the switch version operation
func NewSwitchVersion(ctx *middleware.Context, handler SwitchVersionHandler) *SwitchVersion {
	return &SwitchVersion{Context: ctx, Handler: handler}
}

/*SwitchVersion swagger:route POST /switchVersion /switchVersion switchVersion

Get switch Firmware Version

Get switch Version

*/
type SwitchVersion struct {
	Context *middleware.Context
	Handler SwitchVersionHandler
}

func (o *SwitchVersion) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSwitchVersionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
