// Code generated by go-swagger; DO NOT EDIT.

package switch_version

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/on-network/models"
)

// SwitchVersionOKCode is the HTTP code returned for type SwitchVersionOK
const SwitchVersionOKCode int = 200

/*SwitchVersionOK Successfully returned switch firmware version

swagger:response switchVersionOK
*/
type SwitchVersionOK struct {
}

// NewSwitchVersionOK creates SwitchVersionOK with default headers values
func NewSwitchVersionOK() *SwitchVersionOK {
	return &SwitchVersionOK{}
}

// WriteResponse to the client
func (o *SwitchVersionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*SwitchVersionDefault Error

swagger:response switchVersionDefault
*/
type SwitchVersionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewSwitchVersionDefault creates SwitchVersionDefault with default headers values
func NewSwitchVersionDefault(code int) *SwitchVersionDefault {
	if code <= 0 {
		code = 500
	}

	return &SwitchVersionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the switch version default response
func (o *SwitchVersionDefault) WithStatusCode(code int) *SwitchVersionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the switch version default response
func (o *SwitchVersionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the switch version default response
func (o *SwitchVersionDefault) WithPayload(payload *models.ErrorResponse) *SwitchVersionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the switch version default response
func (o *SwitchVersionDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SwitchVersionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
