// Code generated by go-swagger; DO NOT EDIT.

package controllers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"

	"github.com/RackHD/on-network/restapi/operations"

	"github.com/RackHD/on-network/auth_operations"
)

var bAuthenticated bool

// This file is safe to edit. Once it exists it will not be overwritten
type MyAuthInfo struct {
	token string
}

// NewOnNetworkAPI creates a new OnNetwork instance
func NewOnNetworkAPI(spec *loads.Document) *operations.OnNetworkAPI {

	api := operations.NewOnNetworkAPI(spec)

	// Applies when the "authorization" header is set
	api.BearerAuth = func(token string) (interface{}, error) {
		if auth_operations.ValidateToken(token) {

			authInfo := new(MyAuthInfo)
			authInfo.token = token
			bAuthenticated = true
			return authInfo, nil

		} else {
			return nil, errors.NotImplemented("Invalid token")
		}
	}

	return api
}
