// Code generated by go-swagger; DO NOT EDIT.

package update_switch

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateSwitchHandlerFunc turns a function with the right signature into a update switch handler
type UpdateSwitchHandlerFunc func(UpdateSwitchParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateSwitchHandlerFunc) Handle(params UpdateSwitchParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// UpdateSwitchHandler interface for that can handle valid update switch params
type UpdateSwitchHandler interface {
	Handle(UpdateSwitchParams, interface{}) middleware.Responder
}

// NewUpdateSwitch creates a new http.Handler for the update switch operation
func NewUpdateSwitch(ctx *middleware.Context, handler UpdateSwitchHandler) *UpdateSwitch {
	return &UpdateSwitch{Context: ctx, Handler: handler}
}

/*UpdateSwitch swagger:route POST /updateSwitch /updateSwitch updateSwitch

Update switch firmware

Update switch firmware based on specified switch type and firmware image

*/
type UpdateSwitch struct {
	Context *middleware.Context
	Handler UpdateSwitchHandler
}

func (o *UpdateSwitch) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateSwitchParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
