// Copyright 2017, Dell EMC, Inc.

// Code generated by go-swagger; DO NOT EDIT.

package check_vlan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CheckVlanHandlerFunc turns a function with the right signature into a check vlan handler
type CheckVlanHandlerFunc func(CheckVlanParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CheckVlanHandlerFunc) Handle(params CheckVlanParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CheckVlanHandler interface for that can handle valid check vlan params
type CheckVlanHandler interface {
	Handle(CheckVlanParams, interface{}) middleware.Responder
}

// NewCheckVlan creates a new http.Handler for the check vlan operation
func NewCheckVlan(ctx *middleware.Context, handler CheckVlanHandler) *CheckVlan {
	return &CheckVlan{Context: ctx, Handler: handler}
}

/*CheckVlan swagger:route POST /checkVlan /checkVlan checkVlan

Checks if vlan exists

Check if vlan exists

*/
type CheckVlan struct {
	Context *middleware.Context
	Handler CheckVlanHandler
}

func (o *CheckVlan) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCheckVlanParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
