// Copyright 2017, Dell EMC, Inc.

// Code generated by go-swagger; DO NOT EDIT.

package check_vlan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/RackHD/on-network/models"
)

// CheckVlanOKCode is the HTTP code returned for type CheckVlanOK
const CheckVlanOKCode int = 200

/*CheckVlanOK Successfully returned whether a vlan exists or not

swagger:response checkVlanOK
*/
type CheckVlanOK struct {
}

// NewCheckVlanOK creates CheckVlanOK with default headers values
func NewCheckVlanOK() *CheckVlanOK {
	return &CheckVlanOK{}
}

// WriteResponse to the client
func (o *CheckVlanOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*CheckVlanDefault Error

swagger:response checkVlanDefault
*/
type CheckVlanDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewCheckVlanDefault creates CheckVlanDefault with default headers values
func NewCheckVlanDefault(code int) *CheckVlanDefault {
	if code <= 0 {
		code = 500
	}

	return &CheckVlanDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the check vlan default response
func (o *CheckVlanDefault) WithStatusCode(code int) *CheckVlanDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the check vlan default response
func (o *CheckVlanDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the check vlan default response
func (o *CheckVlanDefault) WithPayload(payload *models.ErrorResponse) *CheckVlanDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the check vlan default response
func (o *CheckVlanDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CheckVlanDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
