// Copyright 2017, Dell EMC, Inc.

// Code generated by go-swagger; DO NOT EDIT.

package switch_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// SwitchConfigHandlerFunc turns a function with the right signature into a switch config handler
type SwitchConfigHandlerFunc func(SwitchConfigParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn SwitchConfigHandlerFunc) Handle(params SwitchConfigParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// SwitchConfigHandler interface for that can handle valid switch config params
type SwitchConfigHandler interface {
	Handle(SwitchConfigParams, interface{}) middleware.Responder
}

// NewSwitchConfig creates a new http.Handler for the switch config operation
func NewSwitchConfig(ctx *middleware.Context, handler SwitchConfigHandler) *SwitchConfig {
	return &SwitchConfig{Context: ctx, Handler: handler}
}

/*SwitchConfig swagger:route POST /switchConfig /switchConfig switchConfig

Get switch running config

Get switch running config

*/
type SwitchConfig struct {
	Context *middleware.Context
	Handler SwitchConfigHandler
}

func (o *SwitchConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSwitchConfigParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
