// Copyright 2017, Dell EMC, Inc.

// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SwitchEndpoint switch endpoint
// swagger:model SwitchEndpoint

type SwitchEndpoint struct {

	// ip
	// Required: true
	IP *string `json:"ip"`

	// password
	// Required: true
	Password *string `json:"password"`

	// switch type
	// Required: true
	SwitchType *string `json:"switchType"`

	// username
	// Required: true
	Username *string `json:"username"`
}

/* polymorph SwitchEndpoint ip false */

/* polymorph SwitchEndpoint password false */

/* polymorph SwitchEndpoint switchType false */

/* polymorph SwitchEndpoint username false */

// Validate validates this switch endpoint
func (m *SwitchEndpoint) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIP(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSwitchType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateUsername(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SwitchEndpoint) validateIP(formats strfmt.Registry) error {

	if err := validate.Required("ip", "body", m.IP); err != nil {
		return err
	}

	return nil
}

func (m *SwitchEndpoint) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	return nil
}

func (m *SwitchEndpoint) validateSwitchType(formats strfmt.Registry) error {

	if err := validate.Required("switchType", "body", m.SwitchType); err != nil {
		return err
	}

	return nil
}

func (m *SwitchEndpoint) validateUsername(formats strfmt.Registry) error {

	if err := validate.Required("username", "body", m.Username); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SwitchEndpoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SwitchEndpoint) UnmarshalBinary(b []byte) error {
	var res SwitchEndpoint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
